package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Amistades generated by hbm2java
 */
@Entity
@Table(name = "AMISTADES", catalog = "indrabook")
public class Amistades implements java.io.Serializable {

	private AmistadesId id;

	public Amistades() {
	}

	public Amistades(AmistadesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)),
			@AttributeOverride(name = "datosPersonalesId1", column = @Column(name = "DATOS_PERSONALES_ID1", nullable = false)) })
	public AmistadesId getId() {
		return this.id;
	}

	public void setId(AmistadesId id) {
		this.id = id;
	}

}
