package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmistadesId generated by hbm2java
 */
@Embeddable
public class AmistadesId implements java.io.Serializable {

	private int datosPersonalesId;
	private int datosPersonalesId1;

	public AmistadesId() {
	}

	public AmistadesId(int datosPersonalesId, int datosPersonalesId1) {
		this.datosPersonalesId = datosPersonalesId;
		this.datosPersonalesId1 = datosPersonalesId1;
	}

	@Column(name = "DATOS_PERSONALES_ID", nullable = false)
	public int getDatosPersonalesId() {
		return this.datosPersonalesId;
	}

	public void setDatosPersonalesId(int datosPersonalesId) {
		this.datosPersonalesId = datosPersonalesId;
	}

	@Column(name = "DATOS_PERSONALES_ID1", nullable = false)
	public int getDatosPersonalesId1() {
		return this.datosPersonalesId1;
	}

	public void setDatosPersonalesId1(int datosPersonalesId1) {
		this.datosPersonalesId1 = datosPersonalesId1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AmistadesId))
			return false;
		AmistadesId castOther = (AmistadesId) other;

		return (this.getDatosPersonalesId() == castOther.getDatosPersonalesId())
				&& (this.getDatosPersonalesId1() == castOther.getDatosPersonalesId1());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDatosPersonalesId();
		result = 37 * result + this.getDatosPersonalesId1();
		return result;
	}

}
