package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalendariosId generated by hbm2java
 */
@Embeddable
public class CalendariosId implements java.io.Serializable {

	private int id;
	private int tipoCalendarioId;
	private int rolesId;

	public CalendariosId() {
	}

	public CalendariosId(int id, int tipoCalendarioId, int rolesId) {
		this.id = id;
		this.tipoCalendarioId = tipoCalendarioId;
		this.rolesId = rolesId;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TIPO_CALENDARIO_ID", nullable = false)
	public int getTipoCalendarioId() {
		return this.tipoCalendarioId;
	}

	public void setTipoCalendarioId(int tipoCalendarioId) {
		this.tipoCalendarioId = tipoCalendarioId;
	}

	@Column(name = "ROLES_ID", nullable = false)
	public int getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(int rolesId) {
		this.rolesId = rolesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalendariosId))
			return false;
		CalendariosId castOther = (CalendariosId) other;

		return (this.getId() == castOther.getId()) && (this.getTipoCalendarioId() == castOther.getTipoCalendarioId())
				&& (this.getRolesId() == castOther.getRolesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getTipoCalendarioId();
		result = 37 * result + this.getRolesId();
		return result;
	}

}
