package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Calendarios generated by hbm2java
 */
@Entity
@Table(name = "CALENDARIOS", catalog = "indrabook")
public class Calendarios implements java.io.Serializable {

	private CalendariosId id;
	private String nombre;
	private String descripcion;

	public Calendarios() {
	}

	public Calendarios(CalendariosId id) {
		this.id = id;
	}

	public Calendarios(CalendariosId id, String nombre, String descripcion) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "tipoCalendarioId", column = @Column(name = "TIPO_CALENDARIO_ID", nullable = false)),
			@AttributeOverride(name = "rolesId", column = @Column(name = "ROLES_ID", nullable = false)) })
	public CalendariosId getId() {
		return this.id;
	}

	public void setId(CalendariosId id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
