package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatosPersonalesLikeComentariosId generated by hbm2java
 */
@Embeddable
public class DatosPersonalesLikeComentariosId implements java.io.Serializable {

	private int datosPersonalesId;
	private int comentariosId;

	public DatosPersonalesLikeComentariosId() {
	}

	public DatosPersonalesLikeComentariosId(int datosPersonalesId, int comentariosId) {
		this.datosPersonalesId = datosPersonalesId;
		this.comentariosId = comentariosId;
	}

	@Column(name = "DATOS_PERSONALES_ID", nullable = false)
	public int getDatosPersonalesId() {
		return this.datosPersonalesId;
	}

	public void setDatosPersonalesId(int datosPersonalesId) {
		this.datosPersonalesId = datosPersonalesId;
	}

	@Column(name = "COMENTARIOS_ID", nullable = false)
	public int getComentariosId() {
		return this.comentariosId;
	}

	public void setComentariosId(int comentariosId) {
		this.comentariosId = comentariosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatosPersonalesLikeComentariosId))
			return false;
		DatosPersonalesLikeComentariosId castOther = (DatosPersonalesLikeComentariosId) other;

		return (this.getDatosPersonalesId() == castOther.getDatosPersonalesId())
				&& (this.getComentariosId() == castOther.getComentariosId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDatosPersonalesId();
		result = 37 * result + this.getComentariosId();
		return result;
	}

}
