package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DatosPersonalesGrupos generated by hbm2java
 */
@Entity
@Table(name = "DATOS_PERSONALES_GRUPOS", catalog = "indrabook")
public class DatosPersonalesGrupos implements java.io.Serializable {

	private DatosPersonalesGruposId id;

	public DatosPersonalesGrupos() {
	}

	public DatosPersonalesGrupos(DatosPersonalesGruposId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)),
			@AttributeOverride(name = "gruposId", column = @Column(name = "GRUPOS_ID", nullable = false)) })
	public DatosPersonalesGruposId getId() {
		return this.id;
	}

	public void setId(DatosPersonalesGruposId id) {
		this.id = id;
	}

}
