package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DatosPersonalesProyectos generated by hbm2java
 */
@Entity
@Table(name = "DATOS_PERSONALES_PROYECTOS", catalog = "indrabook")
public class DatosPersonalesProyectos implements java.io.Serializable {

	private DatosPersonalesProyectosId id;

	public DatosPersonalesProyectos() {
	}

	public DatosPersonalesProyectos(DatosPersonalesProyectosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)),
			@AttributeOverride(name = "proyectosId", column = @Column(name = "PROYECTOS_ID", nullable = false)) })
	public DatosPersonalesProyectosId getId() {
		return this.id;
	}

	public void setId(DatosPersonalesProyectosId id) {
		this.id = id;
	}

}
