package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DatosPersonalesLikeComentarios generated by hbm2java
 */
@Entity
@Table(name = "DATOS_PERSONALES_LIKE_COMENTARIOS", catalog = "indrabook")
public class DatosPersonalesLikeComentarios implements java.io.Serializable {

	private DatosPersonalesLikeComentariosId id;

	public DatosPersonalesLikeComentarios() {
	}

	public DatosPersonalesLikeComentarios(DatosPersonalesLikeComentariosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)),
			@AttributeOverride(name = "comentariosId", column = @Column(name = "COMENTARIOS_ID", nullable = false)) })
	public DatosPersonalesLikeComentariosId getId() {
		return this.id;
	}

	public void setId(DatosPersonalesLikeComentariosId id) {
		this.id = id;
	}

}
