package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatosPersonalesProyectosId generated by hbm2java
 */
@Embeddable
public class DatosPersonalesProyectosId implements java.io.Serializable {

	private int datosPersonalesId;
	private int proyectosId;

	public DatosPersonalesProyectosId() {
	}

	public DatosPersonalesProyectosId(int datosPersonalesId, int proyectosId) {
		this.datosPersonalesId = datosPersonalesId;
		this.proyectosId = proyectosId;
	}

	@Column(name = "DATOS_PERSONALES_ID", nullable = false)
	public int getDatosPersonalesId() {
		return this.datosPersonalesId;
	}

	public void setDatosPersonalesId(int datosPersonalesId) {
		this.datosPersonalesId = datosPersonalesId;
	}

	@Column(name = "PROYECTOS_ID", nullable = false)
	public int getProyectosId() {
		return this.proyectosId;
	}

	public void setProyectosId(int proyectosId) {
		this.proyectosId = proyectosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatosPersonalesProyectosId))
			return false;
		DatosPersonalesProyectosId castOther = (DatosPersonalesProyectosId) other;

		return (this.getDatosPersonalesId() == castOther.getDatosPersonalesId())
				&& (this.getProyectosId() == castOther.getProyectosId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDatosPersonalesId();
		result = 37 * result + this.getProyectosId();
		return result;
	}

}
