package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatosPersonalesGruposId generated by hbm2java
 */
@Embeddable
public class DatosPersonalesGruposId implements java.io.Serializable {

	private int datosPersonalesId;
	private int gruposId;

	public DatosPersonalesGruposId() {
	}

	public DatosPersonalesGruposId(int datosPersonalesId, int gruposId) {
		this.datosPersonalesId = datosPersonalesId;
		this.gruposId = gruposId;
	}

	@Column(name = "DATOS_PERSONALES_ID", nullable = false)
	public int getDatosPersonalesId() {
		return this.datosPersonalesId;
	}

	public void setDatosPersonalesId(int datosPersonalesId) {
		this.datosPersonalesId = datosPersonalesId;
	}

	@Column(name = "GRUPOS_ID", nullable = false)
	public int getGruposId() {
		return this.gruposId;
	}

	public void setGruposId(int gruposId) {
		this.gruposId = gruposId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatosPersonalesGruposId))
			return false;
		DatosPersonalesGruposId castOther = (DatosPersonalesGruposId) other;

		return (this.getDatosPersonalesId() == castOther.getDatosPersonalesId())
				&& (this.getGruposId() == castOther.getGruposId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDatosPersonalesId();
		result = 37 * result + this.getGruposId();
		return result;
	}

}
