package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DatosPersonalesPublicaciones generated by hbm2java
 */
@Entity
@Table(name = "DATOS_PERSONALES_PUBLICACIONES", catalog = "indrabook")
public class DatosPersonalesPublicaciones implements java.io.Serializable {

	private DatosPersonalesPublicacionesId id;

	public DatosPersonalesPublicaciones() {
	}

	public DatosPersonalesPublicaciones(DatosPersonalesPublicacionesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)),
			@AttributeOverride(name = "publicacionesId", column = @Column(name = "PUBLICACIONES_ID", nullable = false)) })
	public DatosPersonalesPublicacionesId getId() {
		return this.id;
	}

	public void setId(DatosPersonalesPublicacionesId id) {
		this.id = id;
	}

}
