package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "EVENTO", catalog = "indrabook")
public class Evento implements java.io.Serializable {

	private EventoId id;
	private Date inicio;
	private Date fin;
	private String descripcion;
	private Integer aviso;

	public Evento() {
	}

	public Evento(EventoId id) {
		this.id = id;
	}

	public Evento(EventoId id, Date inicio, Date fin, String descripcion, Integer aviso) {
		this.id = id;
		this.inicio = inicio;
		this.fin = fin;
		this.descripcion = descripcion;
		this.aviso = aviso;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "calendarioId", column = @Column(name = "CALENDARIO_ID", nullable = false)),
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)) })
	public EventoId getId() {
		return this.id;
	}

	public void setId(EventoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INICIO", length = 19)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIN", length = 19)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "DESCRIPCION", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "AVISO")
	public Integer getAviso() {
		return this.aviso;
	}

	public void setAviso(Integer aviso) {
		this.aviso = aviso;
	}

}
