package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name = "GRUPOS", catalog = "indrabook")
public class Grupos implements java.io.Serializable {

	private GruposId id;
	private String descripcion;

	public Grupos() {
	}

	public Grupos(GruposId id) {
		this.id = id;
	}

	public Grupos(GruposId id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "rolesId", column = @Column(name = "ROLES_ID", nullable = false)) })
	public GruposId getId() {
		return this.id;
	}

	public void setId(GruposId id) {
		this.id = id;
	}

	@Column(name = "DESCRIPCION", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
