package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GruposId generated by hbm2java
 */
@Embeddable
public class GruposId implements java.io.Serializable {

	private int id;
	private int rolesId;

	public GruposId() {
	}

	public GruposId(int id, int rolesId) {
		this.id = id;
		this.rolesId = rolesId;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ROLES_ID", nullable = false)
	public int getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(int rolesId) {
		this.rolesId = rolesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GruposId))
			return false;
		GruposId castOther = (GruposId) other;

		return (this.getId() == castOther.getId()) && (this.getRolesId() == castOther.getRolesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getRolesId();
		return result;
	}

}
