package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Invitados generated by hbm2java
 */
@Entity
@Table(name = "INVITADOS", catalog = "indrabook")
public class Invitados implements java.io.Serializable {

	private InvitadosId id;

	public Invitados() {
	}

	public Invitados(InvitadosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "eventoId", column = @Column(name = "EVENTO_ID", nullable = false)),
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)) })
	public InvitadosId getId() {
		return this.id;
	}

	public void setId(InvitadosId id) {
		this.id = id;
	}

}
