package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvitadosId generated by hbm2java
 */
@Embeddable
public class InvitadosId implements java.io.Serializable {

	private int eventoId;
	private int datosPersonalesId;

	public InvitadosId() {
	}

	public InvitadosId(int eventoId, int datosPersonalesId) {
		this.eventoId = eventoId;
		this.datosPersonalesId = datosPersonalesId;
	}

	@Column(name = "EVENTO_ID", nullable = false)
	public int getEventoId() {
		return this.eventoId;
	}

	public void setEventoId(int eventoId) {
		this.eventoId = eventoId;
	}

	@Column(name = "DATOS_PERSONALES_ID", nullable = false)
	public int getDatosPersonalesId() {
		return this.datosPersonalesId;
	}

	public void setDatosPersonalesId(int datosPersonalesId) {
		this.datosPersonalesId = datosPersonalesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvitadosId))
			return false;
		InvitadosId castOther = (InvitadosId) other;

		return (this.getEventoId() == castOther.getEventoId())
				&& (this.getDatosPersonalesId() == castOther.getDatosPersonalesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventoId();
		result = 37 * result + this.getDatosPersonalesId();
		return result;
	}

}
