package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensajes generated by hbm2java
 */
@Entity
@Table(name = "MENSAJES", catalog = "indrabook")
public class Mensajes implements java.io.Serializable {

	private MensajesId id;
	private Date fecha;
	private String mensaje;
	private Integer leido;

	public Mensajes() {
	}

	public Mensajes(MensajesId id) {
		this.id = id;
	}

	public Mensajes(MensajesId id, Date fecha, String mensaje, Integer leido) {
		this.id = id;
		this.fecha = fecha;
		this.mensaje = mensaje;
		this.leido = leido;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)),
			@AttributeOverride(name = "datosPersonalesIdDestinatario", column = @Column(name = "DATOS_PERSONALES_ID_DESTINATARIO", nullable = false)) })
	public MensajesId getId() {
		return this.id;
	}

	public void setId(MensajesId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "MENSAJE", length = 500)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Column(name = "LEIDO")
	public Integer getLeido() {
		return this.leido;
	}

	public void setLeido(Integer leido) {
		this.leido = leido;
	}

}
