package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajesId generated by hbm2java
 */
@Embeddable
public class MensajesId implements java.io.Serializable {

	private int id;
	private int datosPersonalesId;
	private int datosPersonalesIdDestinatario;

	public MensajesId() {
	}

	public MensajesId(int id, int datosPersonalesId, int datosPersonalesIdDestinatario) {
		this.id = id;
		this.datosPersonalesId = datosPersonalesId;
		this.datosPersonalesIdDestinatario = datosPersonalesIdDestinatario;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "DATOS_PERSONALES_ID", nullable = false)
	public int getDatosPersonalesId() {
		return this.datosPersonalesId;
	}

	public void setDatosPersonalesId(int datosPersonalesId) {
		this.datosPersonalesId = datosPersonalesId;
	}

	@Column(name = "DATOS_PERSONALES_ID_DESTINATARIO", nullable = false)
	public int getDatosPersonalesIdDestinatario() {
		return this.datosPersonalesIdDestinatario;
	}

	public void setDatosPersonalesIdDestinatario(int datosPersonalesIdDestinatario) {
		this.datosPersonalesIdDestinatario = datosPersonalesIdDestinatario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MensajesId))
			return false;
		MensajesId castOther = (MensajesId) other;

		return (this.getId() == castOther.getId()) && (this.getDatosPersonalesId() == castOther.getDatosPersonalesId())
				&& (this.getDatosPersonalesIdDestinatario() == castOther.getDatosPersonalesIdDestinatario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getDatosPersonalesId();
		result = 37 * result + this.getDatosPersonalesIdDestinatario();
		return result;
	}

}
