package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Proyectos generated by hbm2java
 */
@Entity
@Table(name = "PROYECTOS", catalog = "indrabook")
public class Proyectos implements java.io.Serializable {

	private ProyectosId id;
	private String descripcion;

	public Proyectos() {
	}

	public Proyectos(ProyectosId id) {
		this.id = id;
	}

	public Proyectos(ProyectosId id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "datosPersonalesId", column = @Column(name = "DATOS_PERSONALES_ID", nullable = false)) })
	public ProyectosId getId() {
		return this.id;
	}

	public void setId(ProyectosId id) {
		this.id = id;
	}

	@Column(name = "DESCRIPCION", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
