package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PublicacionesComentarios generated by hbm2java
 */
@Entity
@Table(name = "PUBLICACIONES_COMENTARIOS", catalog = "indrabook")
public class PublicacionesComentarios implements java.io.Serializable {

	private PublicacionesComentariosId id;

	public PublicacionesComentarios() {
	}

	public PublicacionesComentarios(PublicacionesComentariosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "publicacionesId", column = @Column(name = "PUBLICACIONES_ID", nullable = false)),
			@AttributeOverride(name = "comentariosId", column = @Column(name = "COMENTARIOS_ID", nullable = false)) })
	public PublicacionesComentariosId getId() {
		return this.id;
	}

	public void setId(PublicacionesComentariosId id) {
		this.id = id;
	}

}
