package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicacionesComentariosId generated by hbm2java
 */
@Embeddable
public class PublicacionesComentariosId implements java.io.Serializable {

	private int publicacionesId;
	private int comentariosId;

	public PublicacionesComentariosId() {
	}

	public PublicacionesComentariosId(int publicacionesId, int comentariosId) {
		this.publicacionesId = publicacionesId;
		this.comentariosId = comentariosId;
	}

	@Column(name = "PUBLICACIONES_ID", nullable = false)
	public int getPublicacionesId() {
		return this.publicacionesId;
	}

	public void setPublicacionesId(int publicacionesId) {
		this.publicacionesId = publicacionesId;
	}

	@Column(name = "COMENTARIOS_ID", nullable = false)
	public int getComentariosId() {
		return this.comentariosId;
	}

	public void setComentariosId(int comentariosId) {
		this.comentariosId = comentariosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicacionesComentariosId))
			return false;
		PublicacionesComentariosId castOther = (PublicacionesComentariosId) other;

		return (this.getPublicacionesId() == castOther.getPublicacionesId())
				&& (this.getComentariosId() == castOther.getComentariosId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPublicacionesId();
		result = 37 * result + this.getComentariosId();
		return result;
	}

}
