package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PublicacionesGrupos generated by hbm2java
 */
@Entity
@Table(name = "PUBLICACIONES_GRUPOS", catalog = "indrabook")
public class PublicacionesGrupos implements java.io.Serializable {

	private PublicacionesGruposId id;

	public PublicacionesGrupos() {
	}

	public PublicacionesGrupos(PublicacionesGruposId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "publicacionesId", column = @Column(name = "PUBLICACIONES_ID", nullable = false)),
			@AttributeOverride(name = "gruposId", column = @Column(name = "GRUPOS_ID", nullable = false)) })
	public PublicacionesGruposId getId() {
		return this.id;
	}

	public void setId(PublicacionesGruposId id) {
		this.id = id;
	}

}
