package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicacionesGruposId generated by hbm2java
 */
@Embeddable
public class PublicacionesGruposId implements java.io.Serializable {

	private int publicacionesId;
	private int gruposId;

	public PublicacionesGruposId() {
	}

	public PublicacionesGruposId(int publicacionesId, int gruposId) {
		this.publicacionesId = publicacionesId;
		this.gruposId = gruposId;
	}

	@Column(name = "PUBLICACIONES_ID", nullable = false)
	public int getPublicacionesId() {
		return this.publicacionesId;
	}

	public void setPublicacionesId(int publicacionesId) {
		this.publicacionesId = publicacionesId;
	}

	@Column(name = "GRUPOS_ID", nullable = false)
	public int getGruposId() {
		return this.gruposId;
	}

	public void setGruposId(int gruposId) {
		this.gruposId = gruposId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicacionesGruposId))
			return false;
		PublicacionesGruposId castOther = (PublicacionesGruposId) other;

		return (this.getPublicacionesId() == castOther.getPublicacionesId())
				&& (this.getGruposId() == castOther.getGruposId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPublicacionesId();
		result = 37 * result + this.getGruposId();
		return result;
	}

}
