package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariosRolesId generated by hbm2java
 */
@Embeddable
public class UsuariosRolesId implements java.io.Serializable {

	private int usuariosId;
	private int rolesId;

	public UsuariosRolesId() {
	}

	public UsuariosRolesId(int usuariosId, int rolesId) {
		this.usuariosId = usuariosId;
		this.rolesId = rolesId;
	}

	@Column(name = "USUARIOS_ID", nullable = false)
	public int getUsuariosId() {
		return this.usuariosId;
	}

	public void setUsuariosId(int usuariosId) {
		this.usuariosId = usuariosId;
	}

	@Column(name = "ROLES_ID", nullable = false)
	public int getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(int rolesId) {
		this.rolesId = rolesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosRolesId))
			return false;
		UsuariosRolesId castOther = (UsuariosRolesId) other;

		return (this.getUsuariosId() == castOther.getUsuariosId()) && (this.getRolesId() == castOther.getRolesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsuariosId();
		result = 37 * result + this.getRolesId();
		return result;
	}

}
