package indra.bbva.curso.datos;
// Generated 20-abr-2018 12:27:47 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsuariosRoles generated by hbm2java
 */
@Entity
@Table(name = "USUARIOS_ROLES", catalog = "indrabook")
public class UsuariosRoles implements java.io.Serializable {

	private UsuariosRolesId id;

	public UsuariosRoles() {
	}

	public UsuariosRoles(UsuariosRolesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "usuariosId", column = @Column(name = "USUARIOS_ID", nullable = false)),
			@AttributeOverride(name = "rolesId", column = @Column(name = "ROLES_ID", nullable = false)) })
	public UsuariosRolesId getId() {
		return this.id;
	}

	public void setId(UsuariosRolesId id) {
		this.id = id;
	}

}
